#!/bin/sh

mkdir -p opk
cp ./vecx.elf opk/vecx.elf
cp ./vecxemu.png opk/icon.png
cp ./LICENSE.md opk/README.txt

# https://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo
print()
	case    ${IFS- } in
	(\ *)   printf  %b\\n "$*";;
	(*)     IFS=\ $IFS
	printf  %b\\n "$*"
	IFS=${IFS#?}
esac

# Create GmenuNx entry file plus other things

print '[Desktop Entry]
Type=Application
Name=VecxEmu
Comment=Vectrex emulator
Exec=vecx.elf %f
Icon=icon
Terminal=false
Type=Application
Categories=emulators;
X-OD-NeedsDownscaling=true' > opk/default."$1".desktop

mksquashfs ./opk vecxemu_"$1".opk -all-root -noappend -no-exports -no-xattrs

rm -r opk
