#!/bin/sh

mkdir -p ipkg/home/retrofw/emus/vecxemu
mkdir -p ipkg/home/retrofw/apps/gmenu2x/sections/emulators
cp ./vecxrs97.elf ipkg/home/retrofw/emus/vecxemu/vecxemu
cp ./vecxemu.png ipkg/home/retrofw/emus/vecxemu/vecxemu.png

cd ipkg

# https://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo
print()
	case    ${IFS- } in
	(\ *)   printf  %b\\n "$*";;
	(*)     IFS=\ $IFS
	printf  %b\\n "$*"
	IFS=${IFS#?}
esac

# Create GmenuNx entry file plus other things

print 'Package: vecxemu
Version: 1.0
Description: Vectrex emulator
Section: emus
Priority: optional
Maintainer: gameblabla
Architecture: mipsel
Homepage: https://github.com/gameblabla/vecxemu
Depends:
Source: https://github.com/gameblabla/vecxemu' > control

print '2.0' > debian-binary

print 'title=VecxEmu
description=Vectrex Emulator
exec=/home/retrofw/emus/vecxemu/vecxemu
clock=600
selectordir=/home/retrofw/roms
selectorfilter=.bin,.vec,.dat' > home/retrofw/apps/gmenu2x/sections/emulators/vecxemu

tar -czvf control.tar.gz control --owner=0 --group=0
tar -czvf data.tar.gz home --owner=0 --group=0
ar rv ../vecxemu.ipk control.tar.gz data.tar.gz debian-binary

cd ..
rm -r ipkg
